version: '3'

networks:
  bot-network:

services:
  bot:
    build: .
    volumes:
      - ..:/10_minute_mail_bot
    command: bash -c 'python -m src.main'
    networks:
      - bot-network
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - cache

  cache:
    image: redis:latest
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bot-network
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}